# Generated by Django 5.0.1 on 2025-12-08 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('grade_level', models.CharField(max_length=50)),
                ('duration_minutes', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True, null=True)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('video_links', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lessons_lesson',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='lessons_les_user_id_ed2142_idx'), models.Index(fields=['slug'], name='lessons_les_slug_ebe546_idx'), models.Index(fields=['is_public', 'slug'], name='lessons_les_is_publ_2243de_idx')],
            },
        ),
    ]
